#!/bin/bash
options=""
switch_string=0
for item in $@
do
		if [[ "$item" = "_"* ]]
		then
				switch_string=1
				item="${item:1}"
		fi
		if [[ "$item" = *"_" ]]
		then
				switch_string=0;
				item="${item:0:-1}"
		fi
		if [ $switch_string == 1 ]
		then
				options+="$item"
				options+="_"
		else
				options+="$item"
				options+=" "
		fi
done

