#!/bin/bash

prin=$(which echo)

$prin -n "Enter command : "
read command
$command &>/dev/null
if [ $? != 0 ]
then
		$prin "command doesn't exist..."
		exit 0
fi
$prin -n  "Enter custom command : "
read custom
$custom &>/dev/null
if [ $? == 0 ]
then
		$prin "This is already a command.. try another"
		exit 0
fi

filename=".customdumpfile"
$(which touch) $filename
$prin "#!/bin/bash" > $filename
$prin "options=\" \"" >> $filename
$prin "for item in \$@" >> $filename
$prin "do" >>$filename
$prin "options=\"\$options \$item\"" >> $filename
$prin "done" >> $filename
$prin "$command \$options" >>$filename
$(which chmod) +x $filename
sudo $(which mv) $filename /usr/local/bin/$custom

$prin "Custom command installed successfully!!"

