#!/bin/bash

prin=$(which echo)

$prin -n "Enter command : "
read command
$command &>/dev/null
if [ $? != 0 ]
then
		if [[ $# != 0 && $1 == "-f"  ]]
		then
				:
		else
			$prin "Can't find this command..."
			$prin "if you want to continue anyway use -f option"
			exit 0
		fi
fi
$prin -n  "Enter custom command : "
read custom
$custom &>/dev/null
if [ $? == 0 ]
then
		$prin "This is already a command.. try another"
		exit 0
fi

filename=".customdumpfile"
$(which touch) $filename
cat framework >> $filename
$prin "$command \$options" >>$filename
$(which chmod) +x $filename
sudo $(which mv) $filename /usr/local/bin/$custom

$prin "Custom command installed successfully!!"

