#!/bin/bash

# run this testfile
# with valid options 
# doesn't matter how many options are given 
options=""

for item in $@
do
		if [[ "$item" = "_"* ]]
		then
				options+="\""
				item="${item:1}"
		fi
		if [[ "$item" = *"_" ]]
		then
				item="${item:0:-1}"
				options+="$item"
				options+="\""
				options+=" "
				continue
				
		fi
		options+="$item"
		options+=" "
done

echo "$options"
string="\"test commit\""
git commit -m $string
