#!/bin/bash

# run this testfile
# with valid options 
# doesn't matter how many options are given 
options=""
switch_string=0
# 0 == false
for item in $@
do
		if [[ "$item" = "_"* ]]
		then
				switch_string=1
				item="${item:1}"
		fi
		if [[ "$item" = *"_" ]]
		then
				switch_string=0;
				item="${item:0:-1}"
		fi
		if [ $switch_string == 1 ]
		then
				options+="$item"
				options+="_"
		else
				options+="$item"
				options+=" "
		fi


done

echo "$options"
# git commit -m $(cat com)
